// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heuracrexfhrpbvdanam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhldXJhY3JleGZocnBidmRhbmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyNzQ0OTAsImV4cCI6MjA1OTg1MDQ5MH0.5genX3zDiqdixech0SuA8YxVwoBE2mCH3lSXapuY1Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);